# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-10 12:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import student.options.fields
import student.options.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(help_text='Example /about/ -page url', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('target_blank', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('youtube_link', student.options.fields.YoutubeLinkField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('home_content_type', models.IntegerField(choices=[(0, 'Bir kontentli'), (1, 'Proqramlar'), (2, 'Event Videolar')], default=0)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0, help_text='Sorting the content', verbose_name='Ordering')),
                ('events', models.ManyToManyField(blank=True, null=True, to='partners.EventVideo')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='HomePageBaseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(default='Home page', max_length=255)),
                ('title', models.CharField(default='Home', max_length=255)),
                ('meta_keywords', models.CharField(default='Azeristudent | You study, we care!', editable=False, max_length=300)),
                ('meta_description', models.TextField(default='2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.', editable=False)),
                ('social_image', models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_country_cover)),
                ('facebook_social_title', models.CharField(default='Azeristudent | You study, we care!', max_length=255)),
                ('facebook_social_description', models.CharField(default='2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.', max_length=255)),
                ('twitter_social_image_alt', models.CharField(default='2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.', max_length=255)),
                ('twitter_social_creator', models.CharField(default='@azeristudent01', max_length=255)),
                ('twitter_social_site', models.CharField(default='@azeristudent01', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Main page configurations',
                'verbose_name': 'Main page',
            },
        ),
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=student.options.tools.get_slider_image)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.HomePageBaseConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('targer_blank', models.BooleanField(default=True)),
                ('link', models.CharField(blank=True, help_text='Not necessary', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='homecontent',
            name='programs',
            field=models.ManyToManyField(blank=True, null=True, to='partners.Programs'),
        ),
    ]
