# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='base_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.HomePageBaseConfig'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='events',
            field=models.ManyToManyField(blank=True, to='partners.EventVideo'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='programs',
            field=models.ManyToManyField(blank=True, to='partners.Programs'),
        ),
    ]
