# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-11 21:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20181110_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
