# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_footercopyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebaseconfig',
            name='page_url',
            field=models.CharField(default='/', help_text='Page url', max_length=255),
        ),
    ]
