# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-12 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20181112_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='register_form',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='register_form',
            field=models.BooleanField(default=False, help_text='if show register form', verbose_name='Register Form'),
        ),
    ]
