# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20181112_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventvideo',
            options={'ordering': ['position'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='partnersays',
            options={'ordering': ['position'], 'verbose_name': 'Partner say', 'verbose_name_plural': 'Partner says'},
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partnersays',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='partnersays',
            name='picture',
            field=models.ImageField(default=1, upload_to='partners/says', verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
