# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-13 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20181112_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerfair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registerfair',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='home_content_type',
            field=models.IntegerField(choices=[(0, 'Bir kontentli'), (1, 'Proqramlar'), (2, 'Event Videolar'), (3, 'Conact form'), (4, 'Partners section')], default=0),
        ),
    ]
