# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20181113_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='targer_blank',
            new_name='target_blank',
        ),
        migrations.RemoveField(
            model_name='registerfair',
            name='full_name',
        ),
        migrations.AddField(
            model_name='registerfair',
            name='cities',
            field=models.ManyToManyField(to='partners.EventVideo'),
        ),
        migrations.AddField(
            model_name='registerfair',
            name='first_name',
            field=models.CharField(default=1, max_length=200, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerfair',
            name='institution',
            field=models.CharField(default=1, max_length=255, verbose_name='Institution name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerfair',
            name='last_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerfair',
            name='signature',
            field=models.CharField(default=1, max_length=200, verbose_name='Signature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerfair',
            name='table_count',
            field=models.PositiveIntegerField(default=0, verbose_name='How many tables each city'),
        ),
        migrations.AlterField(
            model_name='registerfair',
            name='message',
            field=models.TextField(verbose_name='Special comment place'),
        ),
    ]
