# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-15 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_auto_20181115_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvideo',
            name='show_register',
            field=models.BooleanField(default=False, help_text='Select this section if you do wish to have the events displayed in the form', verbose_name='Show register form'),
        ),
    ]
