# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-16 10:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import student.options.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_eventvideo_show_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='How many tables each city')),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_cities_tables', to='partners.EventVideo')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.RemoveField(
            model_name='registerfair',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='registerfair',
            name='table_count',
        ),
        migrations.AddField(
            model_name='mainpageslider',
            name='youtube_link',
            field=student.options.fields.YoutubeLinkField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citiestables',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_tables_register', to='partners.RegisterFair'),
        ),
    ]
