# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_auto_20181117_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerfair',
            name='billing_address',
            field=models.CharField(default=1, max_length=255, verbose_name='Billing Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpageslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_slider_image),
        ),
    ]
