# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_auto_20181121_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerfair',
            name='invoice_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Invoice number'),
            preserve_default=False,
        ),
    ]
