# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_emaillist'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerfair',
            name='reg_loc',
            field=models.PositiveIntegerField(choices=[(0, 'Spring Fair'), (1, 'Fall Fair 2019')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='show_register',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Bir kontentli'), (1, 'Proqramlar'), (2, 'Event Videolar'), (3, 'Conact form'), (4, 'Partners section')], max_length=9, null=True),
        ),
    ]
