# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_auto_20181126_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvideo',
            name='show_register',
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='show_register',
            field=models.ManyToManyField(blank=True, to='partners.BaseMenu'),
        ),
        migrations.AlterField(
            model_name='registerfair',
            name='reg_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_location', to='partners.BaseMenu'),
        ),
    ]
