# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0020_auto_20181126_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_event_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='partnersays',
            name='picture',
            field=models.ImageField(upload_to=student.options.tools.get_partner_says_image, verbose_name='Picture'),
        ),
    ]
