# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_auto_20181206_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_slider_image),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='left_or_right',
            field=models.IntegerField(blank=True, choices=[(0, 'Sağ'), (1, 'Sol')], null=True),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='home_content_type',
            field=models.IntegerField(choices=[(0, 'Bir kontentli'), (1, 'Proqramlar'), (2, 'Event Videolar'), (3, 'Contact form'), (4, 'Partners section')], default=0),
        ),
    ]
