# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_auto_20190319_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebaseconfig',
            name='homepage_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagebaseconfig',
            name='homepage_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
