# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-09 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0025_auto_20191209_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerfair',
            name='full_name',
            field=models.CharField(default='no full name', max_length=300, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerfair',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='registerfair',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name'),
        ),
    ]
