# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0026_auto_20191209_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerfair',
            name='message',
            field=models.TextField(verbose_name='Special comment'),
        ),
    ]
