# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0027_auto_20191209_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerfair',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email Address'),
        ),
    ]
