# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-06 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0032_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', student.options.fields.YoutubeLinkField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Videos',
                'ordering': ('order',),
            },
        ),
    ]
