# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0002_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_system.EmailTemplate'),
        ),
    ]
