# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-17 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='background',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
