# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-17 12:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import student.options.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_flatpage_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatpageDynamicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_type', models.IntegerField(choices=[(0, 'Bir kontentli'), (1, 'Iki kontentli'), (2, 'Əlaqə bölməsi'), (3, 'Xəritə bölməsi'), (4, 'Qalareya bölməsi'), (5, 'Şəkil yazı bölməsi')], default=0)),
                ('order', models.IntegerField(default=0, help_text='Kontentin sıralanma yerini təyin edir', verbose_name='Sırası')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('google_map', student.options.fields.GoogleMapField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flatpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
