# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0003_flatpagedynamiccontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flatpage/image/')),
            ],
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='content',
            field=models.TextField(blank=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='flatgallery',
            name='flatpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage'),
        ),
    ]
