# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_auto_20180917_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpagedynamiccontent',
            name='edu_type',
            field=models.IntegerField(choices=[(0, 'Bir kontentli'), (1, 'Iki kontentli'), (2, 'Əlaqə bölməsi'), (3, 'Xəritə bölməsi'), (4, 'Qalareya bölməsi')], default=0),
        ),
    ]
