# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 11:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import student.options.fields
import student.options.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_title', models.CharField(max_length=255)),
                ('main_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('button_text', models.CharField(default='daha çox', max_length=255)),
                ('button_link', models.CharField(help_text='Example /about/ -page url', max_length=255)),
                ('about_title', models.CharField(default='Haqqımızda', max_length=255)),
                ('about_cover', models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_about_cover)),
                ('services_title', models.CharField(default='Xidmətlər', max_length=255)),
                ('services_text', models.TextField()),
                ('services_button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('services_button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('map_title', models.CharField(default='Xəritə', max_length=255)),
                ('map_location', student.options.fields.GoogleMapField(max_length=255, null=True)),
                ('experts_title', models.CharField(default='Mütəxəsislər', max_length=255)),
                ('experts_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AltMenuAboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('url', models.CharField(help_text='Example /about/ -page url', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.AboutUs')),
            ],
        ),
        migrations.CreateModel(
            name='BaseSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('desription', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(default='Ətraflı', max_length=255)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ImageField(upload_to=student.options.tools.get_slider_image)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slayder',
                'ordering': ('-id',),
                'verbose_name_plural': 'Slayderlər',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad soyad')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('reference_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərildiyi tarix')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesaj',
                'ordering': ('-id',),
                'verbose_name_plural': 'Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='CostOfEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Siyahı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to=student.options.tools.get_country_icon)),
                ('order', models.IntegerField(default=0, verbose_name='Sırası')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('background_image', models.ImageField(upload_to=student.options.tools.get_country_cover)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ölkə haqqında')),
                ('prospect', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Persperktləri')),
                ('expert', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Expert help')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ölkə',
                'ordering': ('order',),
                'verbose_name_plural': 'Ölkələr',
            },
        ),
        migrations.CreateModel(
            name='DoWithUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Do with us!', max_length=255)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_about_cover)),
                ('avatar_full_name', models.CharField(max_length=255)),
                ('avatar_description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('message_text', models.TextField()),
                ('end_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_img', models.ImageField(upload_to=student.options.tools.get_about_cover)),
                ('age_restriction', models.IntegerField(choices=[(0, 'Uşaqlar üçün'), (1, 'Yetkinlər üçün')], default=1)),
                ('age', models.IntegerField(default=0)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Country')),
            ],
        ),
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('backgound_image', models.ImageField(upload_to=student.options.tools.get_about_cover)),
                ('description', models.TextField()),
                ('extra_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Təhsilin növü',
                'ordering': ('order', '-id'),
                'verbose_name_plural': 'Təhsilin növləri',
            },
        ),
        migrations.CreateModel(
            name='EducationContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_type', models.IntegerField(choices=[(0, 'Bir kontentli'), (1, 'Iki kontentli'), (2, 'Əlaqə bölməsi'), (3, 'Xəritə bölməsi'), (4, 'Qalareya bölməsi'), (5, 'Şəkil yazı bölməsi')], default=0)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('google_map', student.options.fields.GoogleMapField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Education')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertsTitleAboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.AboutUs')),
            ],
        ),
        migrations.CreateModel(
            name='FooterHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aşağı menu tənzimləmələri', max_length=255)),
                ('context', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=student.options.tools.get_about_cover)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(help_text='Example /about/ -page url', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('target_blank', models.BooleanField(default=False)),
                ('dropdown', models.BooleanField(default=False)),
                ('muraciet_button', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(null=True, upload_to=student.options.tools.get_about_cover)),
                ('summary', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xəbər',
                'ordering': ('-id',),
                'verbose_name_plural': 'Xəbərlər',
            },
        ),
        migrations.CreateModel(
            name='ProgramMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(help_text='Example /about/ -page url', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.MainMenu')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to=student.options.tools.get_country_cover)),
                ('university_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('review_type', models.IntegerField(choices=[(0, 'Student'), (1, 'Parent')], default=0)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review',
                'ordering': ('-id',),
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sub_description', models.TextField()),
                ('inside_title', models.CharField(blank=True, max_length=255, null=True)),
                ('background', models.ImageField(upload_to=student.options.tools.get_about_cover)),
                ('context', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order', models.IntegerField(default=0, help_text='Sırası')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Servis',
                'ordering': ('order',),
                'verbose_name_plural': 'Servislər',
            },
        ),
        migrations.CreateModel(
            name='ServicesTitleAboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.AboutUs')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('background', models.ImageField(upload_to=student.options.tools.get_about_cover)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program',
                'ordering': ('order',),
                'verbose_name_plural': 'Programlar',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robots', models.CharField(default='noindex', help_text='index, follow', max_length=255)),
                ('keywords', models.CharField(default='Xaricdə Təhsil, təhsil, universitetlər, ölkələr', help_text='hər bir sözü `,`-vergül ilə ayırın', max_length=255)),
                ('description', models.TextField(default='2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.', help_text='sayt haqqında məlumat')),
                ('website_title', models.CharField(default='AzeriStudent', help_text='Saytin adı', max_length=255)),
                ('search_title', models.CharField(default='560 training programs in 21 countries - choose what is right for you', max_length=255)),
                ('services_title', models.CharField(default='Our services', max_length=255)),
                ('services_image', models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_country_cover)),
                ('news_title', models.CharField(default='Xəbərlər', max_length=255)),
                ('about_title', models.CharField(default='Why choose study abroad', max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<p>Text</p>', null=True)),
                ('review_title', models.CharField(default='Rəylər', max_length=255)),
                ('review_cover', models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_about_cover)),
            ],
            options={
                'verbose_name': 'Sayt tənzimləməsi',
                'verbose_name_plural': 'Sayt tənzimləməri',
            },
        ),
        migrations.AddField(
            model_name='educationcontenttype',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='student.Gallery'),
        ),
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.EducationCategory'),
        ),
        migrations.AddField(
            model_name='education',
            name='language',
            field=models.ManyToManyField(to='student.Language'),
        ),
        migrations.AddField(
            model_name='costofeducation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Country'),
        ),
    ]