# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180816_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='programs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.EducationProgram'),
        ),
    ]
