# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 15:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180816_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('context', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tədbirlər',
                'verbose_name': 'Tədbir',
                'ordering': ('-id',),
            },
        ),
    ]
