# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background',
            field=models.ImageField(null=True, upload_to=student.options.tools.get_about_cover),
        ),
    ]
