# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_event_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
    ]
