# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-21 15:23
from __future__ import unicode_literals

from django.db import migrations
import student.options.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_event_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='event',
            name='google_map',
            field=student.options.fields.GoogleMapField(default='POINT (49.85115860712335 40.37782054099786)', max_length=255),
        ),
    ]
