# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20180822_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.TextField(blank=True, null=True, verbose_name='Ərazi'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(null=True, verbose_name='Start date'),
        ),
    ]
