# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20180823_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_country_cover),
        ),
    ]
