# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_review_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Template 1'), (1, 'Template 2')], default=0),
        ),
    ]
