# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20180825_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=student.options.tools.get_about_cover),
        ),
    ]
