# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20180831_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higherspecial',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Country'),
        ),
        migrations.AlterField(
            model_name='univercityprogram',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Country'),
        ),
    ]
