# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-07 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20180906_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationcontenttype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='educationcontenttype',
            name='order',
            field=models.IntegerField(default=0, help_text='Kontentin sıralanma yerini təyin edir', verbose_name='Sırası'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='accommondation',
        ),
        migrations.AddField(
            model_name='education',
            name='accommondation',
            field=models.ManyToManyField(blank=True, null=True, to='student.AccommondationEducation'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='city',
        ),
        migrations.AddField(
            model_name='education',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='student.City'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='program_language',
        ),
        migrations.AddField(
            model_name='education',
            name='program_language',
            field=models.ManyToManyField(blank=True, null=True, to='student.LanguageProgram'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='school_type',
        ),
        migrations.AddField(
            model_name='education',
            name='school_type',
            field=models.ManyToManyField(blank=True, null=True, to='student.SchoolType'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='secondary_program',
        ),
        migrations.AddField(
            model_name='education',
            name='secondary_program',
            field=models.ManyToManyField(blank=True, null=True, to='student.SecondaryProgram'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='specials',
        ),
        migrations.AddField(
            model_name='education',
            name='specials',
            field=models.ManyToManyField(blank=True, null=True, to='student.HigherSpecial'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='univercity_program',
        ),
        migrations.AddField(
            model_name='education',
            name='univercity_program',
            field=models.ManyToManyField(blank=True, null=True, to='student.UnivercityProgram'),
        ),
    ]
