# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20180907_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(upload_to=student.options.tools.get_about_cover)),
                ('main_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Gallery')),
            ],
        ),
    ]
