# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_educationcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcontact',
            name='univercity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Education'),
        ),
    ]
