# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-15 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20180910_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseslider',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='educationcategory',
            options={'ordering': ('order', '-id')},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='websitesetings',
            options={},
        ),
    ]
