# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-31 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20180921_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj'),
        ),
    ]
