# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-20 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_contactus_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Social Media Name')),
                ('icon', models.ImageField(upload_to='social/media/icon', verbose_name='Social Media Icon')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SocialMediaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(verbose_name='Link')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_user', to='student.SocialMediaList')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='review',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_review', to='student.SocialMediaUser'),
        ),
    ]
