# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20181220_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='social_media',
        ),
        migrations.AddField(
            model_name='socialmediauser',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_review', to='student.Review'),
        ),
    ]
