# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20181220_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediauser',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='socialmediauser',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
    ]
