# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-24 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_websitesetings_successful_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.PositiveIntegerField(default=0, verbose_name=((0, 'Table'), (1, 'Sade'), (2, 'Əlaqə bölməsi')))),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('collapsible', models.BooleanField(default=False, help_text='əgər yığılan content istəyirsinizsə bu hissəni seçin', verbose_name='is collapsible')),
                ('short_text', models.TextField(blank=True, null=True, verbose_name='Short text')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('date', models.CharField(max_length=255, verbose_name='Exhibition Date')),
                ('cover_image', models.ImageField(upload_to=student.options.tools.get_exhibition_cover_path, verbose_name='Cover Image')),
                ('participant_image', models.ImageField(upload_to=student.options.tools.get_participant_image_path, verbose_name='Participant Image')),
                ('participant_title', models.CharField(default='Participants of the exhibition Education Abroad', max_length=255, verbose_name='Participant title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionsCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('registration_button', models.BooleanField(default=False, help_text='Əgər contentin sonunda registration button görünməyini istəyirsizsə bu sahəni seçin', verbose_name='Registration button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions_countries', to='student.Exhibitions')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionTableContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_table_content', to='student.EducationContentType')),
            ],
        ),
        migrations.AddField(
            model_name='exhibitioncontenttype',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_content_type', to='student.ExhibitionsCountries'),
        ),
    ]
