# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-24 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_auto_20190124_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitioncontenttype',
            name='content_type',
            field=models.IntegerField(default=0, verbose_name=((0, 'Table'), (1, 'Sade'), (2, 'Əlaqə bölməsi'))),
        ),
    ]
