# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20190124_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitiontablecontent',
            name='fk',
        ),
        migrations.AddField(
            model_name='exhibitioncontenttype',
            name='table_content',
            field=models.ManyToManyField(blank=True, related_name='exhibition_table_content', to='student.ExhibitionTableContent'),
        ),
        migrations.AlterField(
            model_name='exhibitioncontenttype',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'Table'), (1, 'Sade'), (2, 'Əlaqə bölməsi')], default=0),
        ),
    ]
