# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20190124_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitioncontenttype',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='exhibitionscountries',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='exhibitioncontenttype',
            name='google_map',
            field=student.options.fields.GoogleMapField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibitioncontenttype',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='exhibitionscountries',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='exhibitioncontenttype',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'Table'), (1, 'Sade'), (2, 'Əlaqə bölməsi'), (3, 'Xəritə bölməsi')], default=0),
        ),
    ]
