# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-24 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import student.options.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20190124_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitioncontenttype',
            name='google_map',
        ),
        migrations.AddField(
            model_name='exhibitions',
            name='contact_form',
            field=models.BooleanField(default=True, verbose_name='Contact Form'),
        ),
        migrations.AddField(
            model_name='exhibitions',
            name='google_map',
            field=student.options.fields.GoogleMapField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitioncontenttype',
            name='content_type',
            field=models.IntegerField(choices=[(0, 'Table'), (1, 'Sade')], default=0),
        ),
    ]
