# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_auto_20190124_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_exhibitions', to='student.Exhibitions'),
        ),
    ]
