# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-28 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_event_exhibition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitions',
            name='google_map',
        ),
    ]
