# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_remove_exhibitions_google_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_reserve_date', to='student.ContactUs')),
            ],
            options={
                'verbose_name': 'Reservation Date',
                'verbose_name_plural': 'Reservation Dates',
                'ordering': ('-created_at',),
            },
        ),
    ]
