# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-12 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_websitesetings_reservation_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AddField(
            model_name='education',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Change if you want to order on the list'),
        ),
    ]
