# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-10 12:23
from __future__ import unicode_literals

from django.db import migrations
import student.options.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_insurance_insurancecontenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecontenttype',
            name='youtube_video',
            field=student.options.fields.YoutubeLinkField(blank=True, help_text='2 No-lu kontent üçün video', null=True),
        ),
    ]
