# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-11 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_applysettings_connectapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdate',
            name='city',
            field=models.PositiveIntegerField(choices=[(0, 'Baki'), (1, 'Gence')], default=0),
        ),
        migrations.AddField(
            model_name='reservationdate',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Country'),
        ),
        migrations.AddField(
            model_name='reservationdate',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Education'),
        ),
    ]
