# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-13 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_auto_20200311_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdate',
            name='city',
        ),
    ]
