# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0051_remove_reservationdate_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='uniLogoSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniName', models.CharField(max_length=250, null=True, unique=True, verbose_name='university name')),
                ('uniLogo', models.ImageField(null=True, upload_to='')),
                ('uniUrl', models.URLField(max_length=500, null=True)),
                ('slideLimit', models.IntegerField(null=True)),
            ],
        ),
    ]
