# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_unilogoslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilogoslider',
            name='uniLogo',
            field=models.ImageField(null=True, upload_to='unilogo/'),
        ),
    ]
