# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_auto_20201223_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqquestion',
            name='questionicon',
        ),
        migrations.AddField(
            model_name='faqquestiontype',
            name='questionicon',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
