# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0053_auto_20201208_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilogoslider',
            name='slideLimit',
            field=models.IntegerField(null=True, verbose_name='show logo limit'),
        ),
        migrations.AlterField(
            model_name='unilogoslider',
            name='uniLogo',
            field=models.ImageField(null=True, upload_to='unilogo/', verbose_name='university logo'),
        ),
        migrations.AlterField(
            model_name='unilogoslider',
            name='uniUrl',
            field=models.URLField(max_length=500, null=True, verbose_name='university url'),
        ),
    ]
