# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_remove_unilogoslider_slidelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='slideImageLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=5, null=True)),
            ],
        ),
    ]
