# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-18 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_auto_20210118_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
