# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-08 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0056_slideimagelimit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slideImageLimit',
        ),
    ]
