# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0057_delete_slideimagelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetings',
            name='uni_logo_count',
            field=models.IntegerField(default=5),
        ),
    ]
