# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-25 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0057_facoverimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaCoverImage',
            new_name='FaqCoverImage',
        ),
    ]
