# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-25 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0058_auto_20210125_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaqCoverImage',
        ),
    ]
