# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-11 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0058_websitesetings_uni_logo_count'),
        ('student', '0053_auto_20201223_1500'),
    ]

    operations = [
    ]
