# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-25 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0059_delete_faqcoverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetings',
            name='faq_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='faq-cover'),
        ),
    ]
