# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-18 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0060_merge_20210118_0752'),
        ('student', '0056_faqquestion_answer'),
    ]

    operations = [
    ]
