# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-25 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0061_merge_20210118_0840'),
        ('student', '0060_websitesetings_faq_cover_image'),
    ]

    operations = [
    ]
