# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_auto_20201228_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='uni_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
