# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_auto_20201228_1718'),
        ('student', '0060_websitesetings_faq_cover_image'),
    ]

    operations = [
    ]
