# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-02-01 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_merge_20210125_1937'),
        ('student', '0065_auto_20201228_1718'),
    ]

    operations = [
    ]
