# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-03 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0066_merge_20210302_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.currencies'),
        ),
    ]
