# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-15 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0066_merge_20210201_2145'),
        ('student', '0068_auto_20210527_1350'),
    ]

    operations = [
    ]
